language: go
go:
  - 1.12

services:
  - docker



before_install:
- mkdir -p ${HOME}/gopath/src/github.com/kabanero-io/kabanero-rest-services
- mkdir -p /usr/local/bin
- rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/kabanero-io/kabanero-rest-services
- export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/kabanero-io/kabanero-rest-services
- cd ${HOME}/gopath/src/github.com/kabanero-io/kabanero-rest-services
- if [ ! -z ${DOCKER_USERNAME} ]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD || true; fi


script:
#- make check
- make build-image

deploy:
- provider: script
  script: make push-image
  on:
     tags: true
     condition: ${DOCKER_USERNAME} && ${DOCKER_PASSWORD}
- provider: script
  script: make push-image
  on:
     all_branches: true
     condition: ${DOCKER_USERNAME} && ${DOCKER_PASSWORD}

#cache:
#  directories:
#    - vendor 
