consumes:
- application/io.goswagger.examples.todo-list.v1+json
info:
  description: For the Kabanero REST service
  title: Kabanero REST API
  version: 1.0.0

definitions:
  message:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        minLength: 1
    
  kabaneroStack:
    type: object
    properties:
      name:
        type: string
      status:
        type: array
        items:
          type: object
          properties:
            status:
              type: string
            version:
              type: string
            digest check: 
              type: string
            image digest:
              type: string
            kabanero digest:
              type: string
    
  stacksList:
    type: object
    properties:
      kabanero stacks:
        type: array
        items:
          $ref: '#/definitions/kabaneroStack'
      
    
  describeStack:
    type: object
    properties:
      name: 
        type: string
      version:
        type: string
      project:
        type: string
      image:
        type: string
      status:
        type: string
      digest check:
        type: string
      image digest:
        type: string
      kabanero digest:
        type: string
            
  # END stack related defs 
  
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string


paths:
  /:
    get:
      tags:
        - message
      responses:
        200:
          description: standard message response
          schema:
            $ref: "#/definitions/message"
  /test:
    get:
      tags:
        - message
      responses:
        200:
          description: standard message response
          schema:
            $ref: "#/definitions/message"
              

  /v1/stacks:
    get:
      operationId: list
      responses:
        200:
          description: login successful
          schema:
            $ref: '#/definitions/stacksList'
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  
  /v1/describe/stacks/{stackName}/versions/{version}:
    get:
      operationId: describe
      parameters:
      - in: path
        name: stackName
        type: string
        required: true
      - in: path
        name: version
        type: string
        required: true
      responses:
        200:
          description: describe stack
          schema:
            $ref: '#/definitions/describeStack'
            
produces:
- application/io.goswagger.examples.todo-list.v1+json
schemes:
- http
swagger: "2.0"
  